### ISSUE TITLE
Parallel asyncio tasks not running in worker

### ISSUE THREAD

**Issue by txomon** [erdewit/distex#7]
Hello, I have been reading your project and it looks really interesting. however I have noted that even if in the case of async functions you use an asyncio loop, the way you run it the worker wastes this effort.

https://github.com/erdewit/distex/blob/ee09e41d6c70178f0f77786d30556527391fe951/distex/processor.py#L41-L65

Is doing one async task after another instead of using `asyncio.ensure_future()` and keeping track of the tasks to submit them to the host.

Also, I haven't seen any resource monitoring code that chooses the best worker, or if this previous point is implemented, makes sure the worker is not overwhelmed.

**Comment by erdewit** [comment]
> Is doing one async task after another instead of using asyncio.ensure_future()

The idea is that the tasks are CPU bound, so no attempt is made to run async tasks parallel in a single worker. It is straightforward to submit an async task that spawns as much coroutines as it wants though. Also it's possible to start multiple workers per CPU, which is what theadpools tend to do by default.

> Also, I haven't seen any resource monitoring code that chooses the best worker

Each worker has a task queue (default size 2) and the pool's job is basically to keep these queues filled.

**Comment by txomon** [comment]
Oh ok, in my case it's interesting because my workers are network
intensive, so having a distributed system would definitely help.

Cheers,

Javier
