### ISSUE TITLE
do the tests pass?

### ISSUE THREAD

**Issue by cmorgan** [erdewit/distex#8]
Hi, i tried to get this running on a linux server but the pool exited without message. I then tried to run the tests but the appear to hang.

Could you confirm that the tests run before i start debugging my setup?
Thanks!

**Comment by erdewit** [comment]
The tests pass just fine. Remember that an event loop must be started otherwise a program will exit without doing anything.

**Comment by cmorgan** [comment]
In the 1st  example on readme.rst where you map over pool, the loop is not started....how does this work? Thanks
